version: '2.1'
services:
    mysql:
        image: mysql:5.7
        environment:
            - MYSQL_USER=airflow
            - MYSQL_PASSWORD=airflow
            - MYSQL_DATABASE=airflow
            - MYSQL_PORT=3306
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "3306:3306"
        volumes:
            - ./data:/var/lib/mysql

    webserver:
        image: airflow-pipeline:latest
        restart: always
        depends_on:
            - mysql
        environment:
            - LOAD_EX=y
            - EXECUTOR=Local
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

volumes:
  data: {}