version: '2.1'
services:
    mysql:
        image: mysql:8.0.14
        environment:
            - MYSQL_USER=airflow
            - MYSQL_PASSWORD=airflow
            - MYSQL_DATABASE=airflow
            - MYSQL_PORT=3307
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - "3307:3306"
        volumes:
            - ./data/mysql:/var/lib/mysql
            - ./resources/mysql-sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    webserver:
        image: yevdeveloper/airflow-pipeline:latest
        restart: always
        depends_on:
            - mysql
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - ./dags:/usr/local/airflow/dags
            #- ${PWD}/requirements.txt:/usr/local/airflow/requirements.txt
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

volumes:
  data: {}