version: '2.1'
services:
    postgres:
        image: mysql:5.7
        environment:
            - MYSQL_USER=airflow
            - MYSQL_PASSWORD=airflow
            - MYSQL_DATABASE=airflow
            - MYSQL_ROOT_PASSWORD=root
        volumes:
          - ./mysql-dump:/docker-entrypoint-initdb.d

    webserver:
        image: airflow-pipeline:1.10.1
        restart: always
        depends_on:
            - mysql
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - ./dags:/usr/local/airflow/dags
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3
